/**
 * @file Matriz mínima de permissões do BK-MF0-02.
 *
 * As roles vêm diretamente de RF02. Esta matriz é a fonte canónica usada pelos
 * guards backend e pelo contrato devolvido ao frontend.
 */

export const Permission = Object.freeze({
    DASHBOARD_READ: "dashboard.read",
    USERS_MANAGE: "users.manage",
    COMPANY_READ: "company.read",
    COMPANY_WRITE: "company.write",
    ACCOUNTING_READ: "accounting.read",
    ACCOUNTING_WRITE: "accounting.write",
    FISCAL_PERIODS_READ: "fiscal-periods.read",
    FISCAL_PERIODS_MANAGE: "fiscal-periods.manage",
    CUSTOMERS_READ: "customers.read",
    CUSTOMERS_WRITE: "customers.write",
    SUPPLIERS_READ: "suppliers.read",
    SUPPLIERS_WRITE: "suppliers.write",
    ITEMS_READ: "items.read",
    ITEMS_WRITE: "items.write",
    WAREHOUSES_READ: "warehouses.read",
    WAREHOUSES_WRITE: "warehouses.write",
    VAT_RATES_READ: "vat-rates.read",
    VAT_RATES_WRITE: "vat-rates.write",
    SALES_READ: "sales.read",
    SALES_WRITE: "sales.write",
    SALES_APPROVE: "sales.approve",
    PURCHASES_READ: "purchases.read",
    PURCHASES_WRITE: "purchases.write",
    PURCHASES_APPROVE: "purchases.approve",
    PURCHASE_APPROVAL_HISTORY_READ: "purchase-approval-history.read",
    INVENTORY_READ: "inventory.read",
    INVENTORY_WRITE: "inventory.write",
    TAX_READ: "tax.read",
    TREASURY_READ: "treasury.read",
    TREASURY_WRITE: "treasury.write",
    IMPORTS_WRITE: "imports.write",
    COMPLIANCE_READ: "compliance.read",
    REPORTS_READ: "reports.read",
    CASHFLOW_FORECAST_READ: "cashflow-forecast.read",
    OPERATIONAL_REPORTS_READ: "operational-reports.read",
    EXECUTIVE_KPIS_READ: "executive-kpis.read",
    AI_READ: "ai.read",
    AI_WRITE: "ai.write",
    AI_CHAT_USE: "ai.chat.use",
    AI_SETTINGS_MANAGE: "ai.settings.manage",
    AI_ANALYSIS_RUN: "ai.analysis.run",
    AI_SUGGESTIONS_READ: "ai.suggestions.read",
    AI_SUGGESTIONS_MANAGE: "ai.suggestions.manage",
    AI_ALERTS_READ: "ai.alerts.read",
    AI_ALERTS_MANAGE: "ai.alerts.manage",
    AI_INSIGHTS_READ: "ai.insights.read",
    AI_INSIGHTS_MANAGE: "ai.insights.manage",
    REMINDERS_WRITE: "reminders.write",
    TASKS_WRITE: "tasks.write",
    NOTIFICATIONS_READ: "notifications.read",
    AUDIT_READ: "audit.read",
    INTEGRATIONS_READ: "integrations.read",
    SUBSCRIPTIONS_MANAGE: "subscriptions.manage",
});

const rolePermissions = {
    ADMIN: Object.values(Permission),
    GESTOR: [
        Permission.DASHBOARD_READ,
        Permission.USERS_MANAGE,
        Permission.COMPANY_READ,
        Permission.COMPANY_WRITE,
        Permission.ACCOUNTING_READ,
        Permission.FISCAL_PERIODS_READ,
        Permission.FISCAL_PERIODS_MANAGE,
        Permission.CUSTOMERS_READ,
        Permission.CUSTOMERS_WRITE,
        Permission.SUPPLIERS_READ,
        Permission.ITEMS_READ,
        Permission.WAREHOUSES_READ,
        Permission.VAT_RATES_READ,
        Permission.VAT_RATES_WRITE,
        Permission.SALES_READ,
        Permission.SALES_WRITE,
        Permission.SALES_APPROVE,
        Permission.PURCHASES_READ,
        Permission.PURCHASES_WRITE,
        Permission.PURCHASES_APPROVE,
        Permission.PURCHASE_APPROVAL_HISTORY_READ,
        Permission.INVENTORY_READ,
        Permission.INVENTORY_WRITE,
        Permission.TREASURY_READ,
        Permission.REPORTS_READ,
        Permission.CASHFLOW_FORECAST_READ,
        Permission.OPERATIONAL_REPORTS_READ,
        Permission.EXECUTIVE_KPIS_READ,
        Permission.AI_READ,
        Permission.AI_WRITE,
        Permission.AI_CHAT_USE,
        Permission.AI_ANALYSIS_RUN,
        Permission.AI_SUGGESTIONS_READ,
        Permission.AI_SUGGESTIONS_MANAGE,
        Permission.AI_ALERTS_READ,
        Permission.AI_ALERTS_MANAGE,
        Permission.AI_INSIGHTS_READ,
        Permission.AI_INSIGHTS_MANAGE,
        Permission.REMINDERS_WRITE,
        Permission.TASKS_WRITE,
        Permission.NOTIFICATIONS_READ,
        Permission.SUBSCRIPTIONS_MANAGE,
    ],
    CONTABILISTA: [
        Permission.DASHBOARD_READ,
        Permission.COMPANY_READ,
        Permission.COMPANY_WRITE,
        Permission.ACCOUNTING_READ,
        Permission.ACCOUNTING_WRITE,
        Permission.FISCAL_PERIODS_READ,
        Permission.FISCAL_PERIODS_MANAGE,
        Permission.CUSTOMERS_READ,
        Permission.SUPPLIERS_READ,
        Permission.SUPPLIERS_WRITE,
        Permission.ITEMS_READ,
        Permission.WAREHOUSES_READ,
        Permission.VAT_RATES_READ,
        Permission.VAT_RATES_WRITE,
        Permission.SALES_READ,
        Permission.SALES_WRITE,
        Permission.PURCHASES_READ,
        Permission.PURCHASES_WRITE,
        Permission.INVENTORY_READ,
        Permission.TAX_READ,
        Permission.TREASURY_READ,
        Permission.TREASURY_WRITE,
        Permission.IMPORTS_WRITE,
        Permission.COMPLIANCE_READ,
        Permission.REPORTS_READ,
        Permission.AI_READ,
        Permission.AI_CHAT_USE,
        Permission.AI_ANALYSIS_RUN,
        Permission.AI_INSIGHTS_READ,
        Permission.AI_INSIGHTS_MANAGE,
        Permission.REMINDERS_WRITE,
        Permission.TASKS_WRITE,
        Permission.NOTIFICATIONS_READ,
    ],
    OPERACIONAL: [
        Permission.DASHBOARD_READ,
        Permission.COMPANY_READ,
        Permission.CUSTOMERS_READ,
        Permission.CUSTOMERS_WRITE,
        Permission.SUPPLIERS_READ,
        Permission.SUPPLIERS_WRITE,
        Permission.ITEMS_READ,
        Permission.ITEMS_WRITE,
        Permission.WAREHOUSES_READ,
        Permission.WAREHOUSES_WRITE,
        Permission.VAT_RATES_READ,
        Permission.SALES_READ,
        Permission.SALES_WRITE,
        Permission.PURCHASES_READ,
        Permission.PURCHASES_WRITE,
        Permission.INVENTORY_READ,
        Permission.INVENTORY_WRITE,
        Permission.TREASURY_READ,
        Permission.TREASURY_WRITE,
        Permission.REPORTS_READ,
        Permission.OPERATIONAL_REPORTS_READ,
        Permission.REMINDERS_WRITE,
        Permission.TASKS_WRITE,
        Permission.NOTIFICATIONS_READ,
    ],
    AUDITOR: [
        Permission.DASHBOARD_READ,
        Permission.COMPANY_READ,
        Permission.ACCOUNTING_READ,
        Permission.FISCAL_PERIODS_READ,
        Permission.CUSTOMERS_READ,
        Permission.SUPPLIERS_READ,
        Permission.ITEMS_READ,
        Permission.WAREHOUSES_READ,
        Permission.VAT_RATES_READ,
        Permission.SALES_READ,
        Permission.PURCHASES_READ,
        Permission.PURCHASE_APPROVAL_HISTORY_READ,
        Permission.INVENTORY_READ,
        Permission.TAX_READ,
        Permission.COMPLIANCE_READ,
        Permission.REMINDERS_WRITE,
        Permission.NOTIFICATIONS_READ,
        Permission.AUDIT_READ,
    ],
};

/**
 * Devolve as permissões associadas a uma role canónica.
 *
 * @param {string | null | undefined} role - Role ativa no contexto da empresa.
 * @returns {string[]} Lista de permissões funcionais.
 */
export function getPermissionsForRole(role) {
    return rolePermissions[role] ?? [];
}

/**
 * Verifica se uma role possui determinada permissão.
 *
 * @param {string | null | undefined} role - Role ativa no contexto da empresa.
 * @param {string} permission - Permissão funcional a verificar.
 * @returns {boolean} `true` quando a role inclui a permissão.
 */
export function hasPermission(role, permission) {
    return getPermissionsForRole(role).includes(permission);
}
