/**
 * @file Contrato frontend das permissões devolvidas por `GET /api/permissions/me`.
 */

export const Permission = {
  DASHBOARD_READ: "dashboard.read",
  USERS_MANAGE: "users.manage",
  COMPANY_READ: "company.read",
  COMPANY_WRITE: "company.write",
  ACCOUNTING_READ: "accounting.read",
  ACCOUNTING_WRITE: "accounting.write",
  FISCAL_PERIODS_READ: "fiscal-periods.read",
  FISCAL_PERIODS_MANAGE: "fiscal-periods.manage",
  CUSTOMERS_READ: "customers.read",
  CUSTOMERS_WRITE: "customers.write",
  SUPPLIERS_READ: "suppliers.read",
  SUPPLIERS_WRITE: "suppliers.write",
  ITEMS_READ: "items.read",
  ITEMS_WRITE: "items.write",
  WAREHOUSES_READ: "warehouses.read",
  WAREHOUSES_WRITE: "warehouses.write",
  VAT_RATES_READ: "vat-rates.read",
  VAT_RATES_WRITE: "vat-rates.write",
  SALES_READ: "sales.read",
  SALES_WRITE: "sales.write",
  SALES_APPROVE: "sales.approve",
  PURCHASES_READ: "purchases.read",
  PURCHASES_WRITE: "purchases.write",
  PURCHASES_APPROVE: "purchases.approve",
  PURCHASE_APPROVAL_HISTORY_READ: "purchase-approval-history.read",
  INVENTORY_READ: "inventory.read",
  INVENTORY_WRITE: "inventory.write",
  TAX_READ: "tax.read",
  TREASURY_READ: "treasury.read",
  TREASURY_WRITE: "treasury.write",
  IMPORTS_WRITE: "imports.write",
  COMPLIANCE_READ: "compliance.read",
  REPORTS_READ: "reports.read",
  CASHFLOW_FORECAST_READ: "cashflow-forecast.read",
  OPERATIONAL_REPORTS_READ: "operational-reports.read",
  EXECUTIVE_KPIS_READ: "executive-kpis.read",
  AI_READ: "ai.read",
  AI_WRITE: "ai.write",
  AI_CHAT_USE: "ai.chat.use",
  AI_SETTINGS_MANAGE: "ai.settings.manage",
  AI_ANALYSIS_RUN: "ai.analysis.run",
  AI_SUGGESTIONS_READ: "ai.suggestions.read",
  AI_SUGGESTIONS_MANAGE: "ai.suggestions.manage",
  AI_ALERTS_READ: "ai.alerts.read",
  AI_ALERTS_MANAGE: "ai.alerts.manage",
  AI_INSIGHTS_READ: "ai.insights.read",
  AI_INSIGHTS_MANAGE: "ai.insights.manage",
  REMINDERS_WRITE: "reminders.write",
  TASKS_WRITE: "tasks.write",
  NOTIFICATIONS_READ: "notifications.read",
  AUDIT_READ: "audit.read",
  INTEGRATIONS_READ: "integrations.read",
  SUBSCRIPTIONS_MANAGE: "subscriptions.manage",
} as const;

export type PermissionName = (typeof Permission)[keyof typeof Permission];
